### ISSUE TITLE
imagemin minifies images in src folder, not destination

### ISSUE THREAD

**Issue by Regaddi** [namics/grunt-terrific-micro-exporter#1]

**Comment by ernscht** [comment]
I just wanted to say:
In my opinion, there was no bug. It worked correct, src files were not touched – at least on windows ;-)

[Our configuration](https://github.com/namics/grunt-terrific-micro-exporter/commit/9ec8e3dbb78e30bec2c94d69b621dfc67169e7ea) was exactly the [imagemin example](https://github.com/gruntjs/grunt-contrib-imagemin#example-config).
